name = "portfolio"
compatibility_date = "2025-01-01"
main = "workers/app.ts"

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAADqc7R9L4pH0o4op"

[assets]
directory = "./dist/client"

[alias]
"virtual:react-router/server-build" = "./dist/server/index.js"

[[d1_databases]]
binding = "portfolio_db"
database_name = "portfolio-db"
database_id = "122d7ae4-5846-47fd-aec8-05176168f84f"

[[send_email]]
name = "EMAIL"
