import type { SVGProps } from "react";

// IconName is generated by vite-plugin-icons-spritesheet (withTypes: true)
// After first build, import from the generated types file instead.
// For now we type it broadly; tighten after generation.
export type IconName = "arrow-right" | "external-link" | "github";

interface IconProps extends SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number;
}

export function Icon({ name, size = 16, className, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      className={className}
      aria-hidden
      focusable="false"
      {...props}
    >
      <use href={`/icons/sprite.svg#${name}`} />
    </svg>
  );
}
