// This file is generated by icon spritesheet generator

export const iconNames = [
  "ArrowRight",
  "Desktop",
  "ExternalLink",
  "Github",
  "Moon",
  "Sun",
  "UtlogiclabsIcon",
  "UtlogiclabsLogoOutlined (1)",
  "UtlogiclabsLogoOutlined",
  "UtlogiclabsLogo",
] as const

export type IconName = typeof iconNames[number]
